### PR TITLE
🎉 Add docker images for apis

### PR DESCRIPTION
**Pull request by eridem**
I added a `Dockerfile` to build an image for all the API scripts.

This is pretty convenience for us due we can fetch the image from our registry instead to use the script directly.

I added a tutorial and description you can read on the `README.md`.

Please be free to change the structure, code and naming to adjust it to your company standard.

PS. It could be great if you guys generate the images and save them in https://hub.docker.com so we can fetch them too! 👍

### CODE REVIEW

**Review by ttheune — COMMENTED** [review]
Overall very nice, however most of the scripts are written in python2.7; so they don't work in the python:3.6.4 image.  Minor changes required to them to make them python3.
Also, documentation says to run 'docker run foxpass' and it should be 'docker run foxpass-api'.

**Comment by eridem** [comment]
Nice catch!

@ttheune I changed to 2.7 from the `Dockerfile` and fix the documentation issues.

I tested the new image in our own CI tool without problems (the `copy_group` action).

**Review by ttheune — APPROVED** [review]
Looks good, thanks for the fixes.  Going to wait for one other check before merging.

Thank you for the submission!

**Comment by eridem** [comment]
@ttheune take your time and check with your team.
Maybe you want to refactor it, change something or improve it! We are not in rush 👍

**Pull request merged**
